[package]
name = "auth-apikey"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi" }
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.2.24"
