[package]
name = "example-cookie-session"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem" }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
async-session = "3.0.0"
