[package]
name = "example-cookie-session"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["cookie"] }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2.24"
