[package]
name = "example-tracing"
version = "0.1.0"
edition = "2018"

[dependencies]
poem = { path = "../../", features = ["tracing"] }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2.20"
