[package]
name = "example-openapi-users-crud"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi", features = ["swagger-ui", "email"] }
slab = "0.4.4"
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread", "sync"] }
tracing-subscriber = "0.2.24"
