[package]
name = "example-openapi-users-crud"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi" }
tokio = { version = "1.12.0", features = ["macros", "rt-multi-thread", "sync"] }
