[package]
name = "example-lambda-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", default-features = false }
poem-lambda = { path = "../../../poem-lambda" }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
