[package]
name = "example-redis-session"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
poem = { workspace = true, features = ["redis-session"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing-subscriber.workspace = true
redis = { version = "0.22.0", features = ["aio", "tokio-comp", "connection-manager"] }
