[package]
name = "example-redis-session"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["redis-session"] }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.9"
redis = { version = "0.21.2", features = ["aio", "tokio-comp", "connection-manager"] }
