[package]
name = "example-custom-extractor"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.130", features = ["derive"] }
tracing-subscriber = "0.2.24"
