[package]
name = "example-openapi-auth-github"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
poem-openapi = { path = "../../../poem-openapi", features = ["swagger-ui"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11.4", default-features = false, features = [
    "rustls-tls",
] }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
