[package]
name = "example-tls"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["tls"]}
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2.24"
