[package]
name = "example-json"
version = "0.1.0"
edition = "2018"

[dependencies]
poem = { path = "../../" }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
