[package]
name = "example-graceful-shutdown"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem", features = ["sse"] }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros", "signal"] }
futures-util = "0.3.17"
tokio-stream = "0.1.7"
tracing-subscriber = "0.2.24"
