[package]
name = "poem-openapi-derive"
version = "2.0.10"
authors = ["sunli <scott_s829@163.com>"]
edition = "2021"
description = "Macros for poem-openapi"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/poem/"
homepage = "https://github.com/poem-web/poem"
repository = "https://github.com/poem-web/poem"
keywords = ["http", "async", "openapi", "swagger"]
categories = ["network-programming", "asynchronous"]

[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.77", features = ["full", "visit-mut"] }
thiserror = "1.0.29"
indexmap = "1.8.2"
regex = "1.5.5"
http = "0.2.5"
mime = "0.3.16"

[package.metadata.workspaces]
independent = true
