[package]
name = "poem-openapi-derive"
version = "2.0.27"
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Macros for poem-openapi"
keywords = ["http", "async", "openapi", "swagger"]
categories = ["network-programming", "asynchronous"]

[lib]
proc-macro = true

[dependencies]
darling = "0.14.1"
proc-macro-crate = "1.1.0"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.77", features = ["full", "visit-mut"] }
thiserror.workspace = true
indexmap = "1.8.2"
regex.workspace = true
http = "0.2.5"
mime.workspace = true

[package.metadata.workspaces]
independent = true
