[package]
name = "example-mongodb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
poem = { path = "../../../poem" }
tokio = { version = "1.12", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mongodb = "2"
futures = "0.3"
tracing-subscriber = "0.2.24"
