[package]
name = "example-graceful-shutdown"
version = "0.1.0"
edition = "2018"

[dependencies]
poem = { path = "../../" }
tokio = { version = "1.10.0", features = ["rt-multi-thread", "macros"] }
futures-util = "0.3.16"
tokio-stream = "0.1.7"
