[package]
name = "poem-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = { path = "../../../poem", features = ["session"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.2.24"
